### ISSUE TITLE
Test failures due to hash randomization?

### ISSUE THREAD

**Issue by eserte** [rizen/Firebase#1]
See http://matrix.cpantesters.org/?dist=Firebase for a pass/fail overview. There are only failures for perl 5.18.0 and newer, which is indicating that the problem may be due to the hash randomization introduced in these perl versions.

**Comment by rizen** [comment]
I believe this is fixed in 1.002

**Comment by eserte** [comment]
There are still other problems with 1.0002 (see http://matrix.cpantesters.org/?dist=Firebase%201.0002 ), but the hash randomization problem looks fixed now.
