### ISSUE TITLE
Update CPAN

### ISSUE THREAD

**Issue by jacqueslareau** [rizen/Firebase#2]
Hi, great module!

Is it possible to release 0.0300 to CPAN?

Thanks!

**Comment by jacqueslareau** [comment]
Hum. 0.0300 is on CPAN but the source is not the same as here. For example, the CPAN release is missing the post method.

**Comment by perlDreamer** [comment]
It's quite possible that I didn't bump the version number for adding POST, PATCH and some other methods.

**Comment by rizen** [comment]
0.0400 was just released to cpan

**Comment by jacqueslareau** [comment]
Great! Thanks :+1:
